on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1' ]

    name: PHP ${{ matrix.php }}

    steps:
    - uses: actions/checkout@v2

    - run: php bug.php
